### PR TITLE
Fix styling of error pages

### PR DESCRIPTION
**Pull request by urbanwide**
Basic version.

I'll let you decide if you like the layout with the error code in larger text @ldodds.

### CODE REVIEW

**Comment by urbanwide** [comment]
Hi @ldodds - do you mean like this? Do you have a preference - a or b below? Thanks

a)
image

b)
image

**Review by ldodds — APPROVED** [review]
Good to merge

**Comment by urbanwide** [comment]
Thanks @ldodds - but did you see there are two options to pick from above? :-)

**Comment by ldodds** [comment]
Sorry scrolled past the images but missed the question. Option b!

**Pull request merged**
