### PR TITLE
Fix homepage case studies download button translations

### PR DESCRIPTION
**Pull request by iant**

### CODE REVIEW

**Comment by urbanwide** [comment]
As discussed with Ian:

For case studies translations implementation, it was decided that two download links would be required for each case study, one to the English download file and one to the Welsh download file, if the Welsh version was available (both to be shown in both languages). The Welsh download link is in Welsh and the English download link in English as below:

Screenshot 2022-11-17 at 17 41 12

So on investigation, there is no Welsh version of the link shown because there is no Welsh case study files available to download on the live site. See: https://energysparks.uk/admin/case_studies

So the main issue is that the Welsh versions of the download files are missing.
Also, we might want to change the way the download links work at some point as it looks a bit clunky with two links. Maybe just have one link in the current language and either not displaying the download link if the file is not available in Welsh or as Ian suggested, disabling the button with "download not available" alt text.

**Comment by ldodds** [comment]
Decision was to:

- only show a single button (in correct language)
- offer download of Welsh case study from Welsh interface if available, otherwise fall back to English
- on English site, offer download of English

**Comment by iant** [comment]
hi @ldodds @urbanwide discussed points (above) are now addressed so I think this pr's ready for another review now.

**Review by urbanwide — APPROVED** [review]
Looks good @iant 👍

**Pull request merged**
